<?php

namespace AppBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository {

    public function listerArmesFamiliales($max) {
        
        $query = $this->_em->createQuery(
                "SELECT p FROM AppBundle:Produit p ORDER BY p.prix ASC");
        $produits = $query->setMaxResults($max)->getResult();
        
        return $produits;
    }
    
    public function listerArmesPrestige($max) {
        
        $qb = $this->_em->createQueryBuilder();
        $query = $qb->select("p")->from("AppBundle:Produit", "p")
                ->orderBy("p.prix", "DESC")->getQuery();
        
//        $query = $this->_em->createQuery(
//                "SELECT p FROM AppBundle:Produit p ORDER BY p.prix DESC");
        $produits = $query->setMaxResults($max)->getResult();
        
        return $produits;
    }

}
