# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\Client: plaintext

    role_hierarchy:
        ROLE_ADMIN: ROLE_MOD
        ROLE_MOD: ROLE_SIMPLE

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        en_base_donnees:
            entity:
                class: AppBundle:Client
                property: login
        en_memoire:
            memory: 
                users:
                    simple:
                        password: simple
                        roles: 'ROLE_SIMPLE'
                    mod:
                        password: mod
                        roles: 'ROLE_MOD'
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            
            provider: en_base_donnees
            
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: /logout
                target: /
            
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            
    access_control:
        - {path: admin/client*, roles: ROLE_ADMIN}
        - {path: admin/*, roles: ROLE_MOD}