# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    mail.compte_emetteur: quicotte@gmail.com
#    parameter_name: value

services:
    
    mail:
        class: AppBundle\Service\MailService
        arguments: ["@mailer", "@logger", "%mail.compte_emetteur%"]
    
    client:
        class: AppBundle\Service\ClientService
        arguments: ["@doctrine.orm.entity_manager", "@logger", "@mail"]



#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
